### ISSUE TITLE
SHOW FULL COLUMNS FROM TABLE many times

### ISSUE THREAD

**Issue by suchoproduction** [nextras/orm#326]
Chcem sa opýtať
Všimol som si že mi v dtazoch v Tracy dáva niektoré veci 2x zasebou
Je to štandardné správanie alebo treba niečo nastaviť?

ms | SQL query
-- | --
0.08 | SET sql_mode = 'TRADITIONAL'
0.10 | SET time_zone = '+01:00'
0.38 | SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME = 'language' ORDER BYCONSTRAINT_NAME	1 row explain
2.22 | SHOW FULL COLUMNS FROM `language`
1.61 | SHOW FULL COLUMNS FROM `language`
0.29 | SELECT `language`.* FROM `language` AS `language` WHERE (`language`.`active` = 1)	2 rows explain
0.60 | SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME = 'user' ORDER BYCONSTRAINT_NAME	2 rows explain
1.95 | SHOW FULL COLUMNS FROM `user`
1.99 | SHOW FULL COLUMNS FROM `user`
0.27 | SELECT `user`.* FROM `user` AS `user` WHERE (`user`.`id` = 1)	1 row explain
1.01 | SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME = 'page' ORDER BYCONSTRAINT_NAME	2 rows explain
2.70 | SHOW FULL COLUMNS FROM `page`
2.12 | SHOW FULL COLUMNS FROM `page`
0.43 | SELECT `page`.* FROM `page` AS `page` WHERE (`page`.`id` = '1')	1 row explain
0.63 | SELECT `language`.* FROM `language` AS `language` WHERE (`language`.`code` = 'sk')	1 row explain
0.88 | SELECT CONSTRAINT_NAME, COLUMN_NAME, REFERENCED_TABLE_NAME, REFERENCED_COLUMN_NAME FROM information_schema.KEY_COLUMN_USAGE WHERE TABLE_SCHEMA = DATABASE() AND REFERENCED_TABLE_NAME IS NOT NULL AND TABLE_NAME = 'page_lang' ORDER BYCONSTRAINT_NAME	2 rows explain
2.80 | SHOW FULL COLUMNS FROM `page_lang`
2.21 | SHOW FULL COLUMNS FROM `page_lang`
0.49 | SELECT `page_lang`.* FROM `page_lang` AS `page_lang` WHERE ((`page_lang`.`lang_id` = 1)) AND(`page_lang`.`page_id` IN (1))	1 row explain
0.44 | SELECT `language`.* FROM `language` AS `language` WHERE (`language`.`code` = 'sk')	1 row explain

**Comment by hrach** [comment]
SHOW FULL COLUMNS by urcite byt nemelo, to by se melo cachovat.
Ostatni dotazy - to tezko rict, obecne se vysledky dotazu necachuji, tzn. kdyz selectujes znovu neco s nejakou podminkou, tak se znovu spusti dotaz.

Jak orm konfigurujes? Pomoci DI extension?

**Comment by suchoproduction** [comment]
Nič výnimočné som nekonfiguroval zatiaľ
Jasné normálne dotazy rozumiem že tam budú toľko krát koľko ich použijem
hlavne ma to `SHOW FULL COLUMNS FROM` zaujímalo prečo je stále 2x za sebou

```
extensions:
    dbal: Nextras\Dbal\Bridges\NetteDI\DbalExtension
    nextras.orm: Nextras\Orm\Bridges\NetteDI\OrmExtension

dbal:
	driver: %database.default.driver%
	host: %database.default.host%
	database: %database.default.name%
	username: %database.default.user%
	password: %database.default.pass%
	connectionTz: auto-offset

nextras.orm:
    model: Magazino\Database\Models\Orm
    repositoryFinder: Magazino\Database\Models\RepositoryFinder
```

Tu je ukážka ako pridávam repository

```
services:
    DeletedFacade: Magazino\Database\Models\Deleted\DeletedFacade
    DeletedRepository:
        class: Magazino\Database\Models\Deleted\DeletedRepository
        arguments: [Magazino\Database\Models\Deleted\DeletedMapper()]
```
